project_id = "xmoqyrcevbggoeoexzey"

[functions.chat-ai]
verify_jwt = true

[functions.chat-ai-demo]
verify_jwt = false

[functions.generate-voice]
verify_jwt = true

[functions.analyze-document]
verify_jwt = true

[functions.generate-document]
verify_jwt = true

[functions.extract-text-ocr]
verify_jwt = true

[functions.create-document-payment]
verify_jwt = true
